DROP TABLE IF EXISTS MOVIE_DTO;
  
CREATE TABLE MOVIE_DTO(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  movieName VARCHAR(250) NOT NULL,
  language VARCHAR(250) NOT NULL,
  genre VARCHAR(250) NOT NULL,
  rating INT NOT NULL,
  releaseDate DATE DEFAULT NULL
);